class Disbursement < Sequel::Model
end

# Table: disbursements
# Columns:
#  id              | integer       | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  week_started_at | date          | NOT NULL
#  amount          | numeric(10,2) | NOT NULL
#  merchant_id     | integer       | NOT NULL
# Indexes:
#  disbursements_pkey | PRIMARY KEY btree (id)
