class Order < Sequel::Model
end

# Table: orders
# Columns:
#  id           | integer                     | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  merchant_id  | integer                     | NOT NULL
#  shopper_id   | integer                     | NOT NULL
#  amount       | numeric(10,2)               | NOT NULL
#  created_at   | timestamp without time zone | NOT NULL
#  completed_at | timestamp without time zone |
# Indexes:
#  orders_pkey | PRIMARY KEY btree (id)
